rethinkdb:
     restart: always
     image: rethinkdb
     ports:
         - "8080"
         - "28015"
         - "29015"
     environment:
         no_proxy: "localhost,127.0.0.1,proxy,swarm,media,rethinkdb,myd-vm23183.hpswlabs.adapps.hp.com"
 
media:
     restart: always
     build: .
     entrypoint: /bin/bash
     dockerfile: Dockerfile.build
     command: -c "make media && sleep infinity"
     working_dir: /go/src/github.com/shipyard/shipyard
     volumes:
         - "./controller/static:/go/src/github.com/shipyard/shipyard/controller/static"
     environment:
         no_proxy: "localhost,127.0.0.1,proxy,swarm,media,rethinkdb,myd-vm23183.hpswlabs.adapps.hp.com"
 
controller:
     restart: always
     build: .
     dockerfile: Dockerfile.build
     entrypoint: /bin/bash
     command: -c "make build && cd controller && ./controller -D server --rethinkdb-addr rethinkdb:28015 -d tcp://myd-vm23183.hpswlabs.adapps.hp.com:3375"
     links:
         - rethinkdb
     volumes:
         - .:/go/src/github.com/shipyard/shipyard
     volumes_from:
         - media
     ports:
         - "8888:8080"
     environment:
         no_proxy: "localhost,127.0.0.1,proxy,swarm,media,rethinkdb,myd-vm23183.hpswlabs.adapps.hp.com" 
